### PR TITLE
Adding camel-upper-case, camel-lower-case, kebab-case and snake-case

### PR DESCRIPTION
**Pull request by JulienRouse**
Hello, i saw your post on Reddit and i was inspired to help a bit. I'm fairly inexperienced with Common Lisp so i hope progressing a bit practicing. Don't hesitate to tell me what must be improved and how to improve the quality of this patch if anything don't fit your standards.

I looked Wikipedia for the camel case, and i saw they used camel-lower-case and camel-upper-case to avoid confusion, so i stole the name but it could also be camel-uppercase and camel-lowercase.

### CODE REVIEW

**Comment by diogoalexandrefranco** [comment]
Hi! Thanks Julien, this is cool :)

Do you think you could make it so that we follow the usual "definitions" of the formats?

- kebab-case is usually all lower-case (Ex: kebab-case).
- in snake-case, we can leave the first letter, but other words usually start with lower case. (Ex: Hello_world, or hello_world).
- camel-case, maybe we should just make one function that leaves the first letter as is in the input, and capitalizes in the other words (ex: "Hello world" to "HelloWorld", and "hello world" to "helloWorld".

Thanks for your PR!

**Comment by JulienRouse** [comment]
I fixed the function to be more in line with what you said to me.

I'm not 100% sure that i tested every case possible, if you see anything i'll happily add what's missing.

**Comment by diogoalexandrefranco** [comment]
Hey JulienRouse.

Thanks for your PR. I refactored a bit the new functions, for consistency (to accept chars too, for example). 

I left your tests as you wrote them and will do the documentation for your new functions now.

Thanks again!

**Comment by JulienRouse** [comment]
I'm glad that was at least a bit useful.

Good luck with this project, cheers mate.

**Pull request merged**
